runtime: nodejs14
env: standard
instance_class: F1
# service: Silsila-E-Quderia
automatic_scaling:
  min_instances: 0
  max_instances: 2
  max_idle_instances: 2
  min_idle_instances: 0
  max_pending_latency: 2s
  min_pending_latency: automatic


  # cool_down_period_sec: 180
  # cpu_utilization:
  #   target_utilization: 0.5
  # target_concurrent_requests: 100